export const metadata = {
  title: "Service - Mindmap",
  description: "Generated by create next app",
};

const ServicePage = () => {
  return <div>ServicePage</div>;
};

export default ServicePage;
