export const metadata = {
  title: "Contact - Mindmap",
  description: "Generated by create next app",
};

const ContactPage = () => {
  return <div className="container">ContactPage</div>;
};

export default ContactPage;
