export const metadata = {
  title: "Price - Mindmap",
  description: "Generated by create next app",
};

const PricePage = () => {
  return (
    <div className="container">PricePage</div>
  )
}

export default PricePage