import AboutSection from "./AboutSection";

export const metadata = {
  title: "About - Mindmap",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div className="">
    <AboutSection />
    </div>
  )
}

export default AboutPage