import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/default/Header";
import Footer from "@/components/default/Footer";
import { ThemeProvider } from "@/components/default/ThemeProvider";
import { UserProvider } from "@auth0/nextjs-auth0/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mindmap",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <ThemeProvider attribute="class" defaultTheme="dark">
            <Header />
            {children}
          </ThemeProvider>
        </UserProvider>
      </body>
    </html>
  );
}
